//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GameEngine {
    
    private string briefingField;
    
    private GameEnginePlayer[] playerField;
    
    private string idField;
    
    private string nameField;
    
    private string turnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Briefing {
        get {
            return this.briefingField;
        }
        set {
            this.briefingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Player", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayer[] Player {
        get {
            return this.playerField;
        }
        set {
            this.playerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string turn {
        get {
            return this.turnField;
        }
        set {
            this.turnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayer {
    
    private string objectivesField;
    
    private GameEnginePlayerShip[] shipField;
    
    private string idField;
    
    private string nameField;
    
    private string emailField;
    
    private string teamField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Objectives {
        get {
            return this.objectivesField;
        }
        set {
            this.objectivesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ship", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShip[] Ship {
        get {
            return this.shipField;
        }
        set {
            this.shipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShip {
    
    private string nameField;
    
    private string statusField;
    
    private string ordersField;
    
    private string raceField;
    
    private string classAbbrevField;
    
    private string classNameField;
    
    private string shipClassField;
    
    private string massField;
    
    private string pointValueField;
    
    private string fTLDriveField;
    
    private GameEnginePlayerShipPosition[] positionField;
    
    private GameEnginePlayerShipHeading[] headingField;
    
    private GameEnginePlayerShipSpeed[] speedField;
    
    private GameEnginePlayerShipCourse[] courseField;
    
    private GameEnginePlayerShipVectorSpeed[] vectorSpeedField;
    
    private GameEnginePlayerShipIconFamily[] iconFamilyField;
    
    private GameEnginePlayerShipMainDrive[] mainDriveField;
    
    private GameEnginePlayerShipArmor[] armorField;
    
    private GameEnginePlayerShipHull[] hullField;
    
    private GameEnginePlayerShipElectronicsFireControl[][] electronicsField;
    
    private GameEnginePlayerShipDefensesScreen[][] defensesField;
    
    private GameEnginePlayerShipWeapons[] weaponsField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Orders {
        get {
            return this.ordersField;
        }
        set {
            this.ordersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Race {
        get {
            return this.raceField;
        }
        set {
            this.raceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClassAbbrev {
        get {
            return this.classAbbrevField;
        }
        set {
            this.classAbbrevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClassName {
        get {
            return this.classNameField;
        }
        set {
            this.classNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShipClass {
        get {
            return this.shipClassField;
        }
        set {
            this.shipClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Mass {
        get {
            return this.massField;
        }
        set {
            this.massField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PointValue {
        get {
            return this.pointValueField;
        }
        set {
            this.pointValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FTLDrive {
        get {
            return this.fTLDriveField;
        }
        set {
            this.fTLDriveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Position", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipPosition[] Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Heading", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipHeading[] Heading {
        get {
            return this.headingField;
        }
        set {
            this.headingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Speed", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipSpeed[] Speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Course", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipCourse[] Course {
        get {
            return this.courseField;
        }
        set {
            this.courseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VectorSpeed", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipVectorSpeed[] VectorSpeed {
        get {
            return this.vectorSpeedField;
        }
        set {
            this.vectorSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IconFamily", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipIconFamily[] IconFamily {
        get {
            return this.iconFamilyField;
        }
        set {
            this.iconFamilyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MainDrive", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipMainDrive[] MainDrive {
        get {
            return this.mainDriveField;
        }
        set {
            this.mainDriveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Armor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipArmor[] Armor {
        get {
            return this.armorField;
        }
        set {
            this.armorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Hull", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipHull[] Hull {
        get {
            return this.hullField;
        }
        set {
            this.hullField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FireControl", typeof(GameEnginePlayerShipElectronicsFireControl), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public GameEnginePlayerShipElectronicsFireControl[][] Electronics {
        get {
            return this.electronicsField;
        }
        set {
            this.electronicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Screen", typeof(GameEnginePlayerShipDefensesScreen), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public GameEnginePlayerShipDefensesScreen[][] Defenses {
        get {
            return this.defensesField;
        }
        set {
            this.defensesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Weapons", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipWeapons[] Weapons {
        get {
            return this.weaponsField;
        }
        set {
            this.weaponsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipPosition {
    
    private string xField;
    
    private string yField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipHeading {
    
    private string headingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string heading {
        get {
            return this.headingField;
        }
        set {
            this.headingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipSpeed {
    
    private string speedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipCourse {
    
    private string courseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string course {
        get {
            return this.courseField;
        }
        set {
            this.courseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipVectorSpeed {
    
    private string speedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipIconFamily {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipMainDrive {
    
    private string initialThrustField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string initialThrust {
        get {
            return this.initialThrustField;
        }
        set {
            this.initialThrustField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipArmor {
    
    private string totalArmorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string totalArmor {
        get {
            return this.totalArmorField;
        }
        set {
            this.totalArmorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipHull {
    
    private string valueField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipElectronicsFireControl {
    
    private string xSSDField;
    
    private string ySSDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xSSD {
        get {
            return this.xSSDField;
        }
        set {
            this.xSSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ySSD {
        get {
            return this.ySSDField;
        }
        set {
            this.ySSDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipDefensesScreen {
    
    private string xSSDField;
    
    private string ySSDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xSSD {
        get {
            return this.xSSDField;
        }
        set {
            this.xSSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ySSD {
        get {
            return this.ySSDField;
        }
        set {
            this.ySSDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipWeapons {
    
    private GameEnginePlayerShipWeaponsPulseTorpedo[] pulseTorpedoField;
    
    private GameEnginePlayerShipWeaponsBeamBattery[] beamBatteryField;
    
    private GameEnginePlayerShipWeaponsSubmunitionPack[] submunitionPackField;
    
    private GameEnginePlayerShipWeaponsPointDefense[] pointDefenseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PulseTorpedo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipWeaponsPulseTorpedo[] PulseTorpedo {
        get {
            return this.pulseTorpedoField;
        }
        set {
            this.pulseTorpedoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BeamBattery", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipWeaponsBeamBattery[] BeamBattery {
        get {
            return this.beamBatteryField;
        }
        set {
            this.beamBatteryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubmunitionPack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipWeaponsSubmunitionPack[] SubmunitionPack {
        get {
            return this.submunitionPackField;
        }
        set {
            this.submunitionPackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PointDefense", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GameEnginePlayerShipWeaponsPointDefense[] PointDefense {
        get {
            return this.pointDefenseField;
        }
        set {
            this.pointDefenseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipWeaponsPulseTorpedo {
    
    private string xSSDField;
    
    private string ySSDField;
    
    private string arcsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xSSD {
        get {
            return this.xSSDField;
        }
        set {
            this.xSSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ySSD {
        get {
            return this.ySSDField;
        }
        set {
            this.ySSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string arcs {
        get {
            return this.arcsField;
        }
        set {
            this.arcsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipWeaponsBeamBattery {
    
    private string xSSDField;
    
    private string ySSDField;
    
    private string ratingField;
    
    private string arcsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xSSD {
        get {
            return this.xSSDField;
        }
        set {
            this.xSSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ySSD {
        get {
            return this.ySSDField;
        }
        set {
            this.ySSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string arcs {
        get {
            return this.arcsField;
        }
        set {
            this.arcsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipWeaponsSubmunitionPack {
    
    private string xSSDField;
    
    private string ySSDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xSSD {
        get {
            return this.xSSDField;
        }
        set {
            this.xSSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ySSD {
        get {
            return this.ySSDField;
        }
        set {
            this.ySSDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GameEnginePlayerShipWeaponsPointDefense {
    
    private string xSSDField;
    
    private string ySSDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xSSD {
        get {
            return this.xSSDField;
        }
        set {
            this.xSSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ySSD {
        get {
            return this.ySSDField;
        }
        set {
            this.ySSDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private GameEngine[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GameEngine")]
    public GameEngine[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
